backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: /assets
collections:
  - name: blog
    label: Blog
    folder: src/markdownPage
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: pagesContent
    label: Pages
    files:
      - file: src/pageContent/index.json
        name: home
        label: HomePage
        fields: 
          - { name: templateKey, label: TemplateKey, widget: hidden, default: indexPage}
          - label: AboutSection
            name: aboutSection
            widget: object
            fields:
               - { name: aboutTitle, label: AboutTitle, widget: string }
               - { name: aboutMe, label: AboutMe, widget: text }
          - label: WorkSection
            name: workSection
            widget: object
            fields:
               - { name: workTitle, label: WorkTitle, widget: string }
               - { name: workDes, label: WorkDes, widget: text } 
               - label: WorkSkills
                 name: workSkills
                 widget: list
                 allow_add: true
                 fields: 
                   - { name: workSkillCate, label: WorkSkillCate, widget: string }
                   - label: WorkSkill
                     name: workSkill
                     widget: list
                     allow_add: true
                     fields: 
                       - { name: workSkillDes, label: WorkSkillDes, widget: text }
          - label: SkillSection
            name: skillSection
            widget: object
            fields:
               - { name: skillTitle, label: SkillTitle, widget: string }
               - { name: skillDes, label: SkillDes, widget: text } 
      - file: src/pageContent/projectPage.json
        name: project
        label: ProjectPage
        fields: 
          - label: ProjectItems
            name: projectItems
            widget: list
            allow_add: true
            fields:
              - {name: projectTitle, label: ProjectTitle, widget: string}
              - {name: projectDes, label: ProjectDes, widget: text}
              - {name: link, label: Link, widget: string}
              - {name: backgroundColor, label: BackgroundColor, widget: string}

      - file: src/pageContent/dailyPageContent.json
        name: dailyPage
        label: DailyPage
        fields: 
             - label: DailyIntro
               name: dailyIntro
               widget: object
               fields:
                  - {name: intro, label: Intro, widget: text}

             - label: DailyDog
               name: dailyDog
               widget: object
               fields :
                  - {name: introDog, label: IntroDog, widget: text}

             - label: DailyUs
               name: dailyUs
               widget: object
               fields :
                  - {name: introUs, label: IntroUs, widget: text}
                  - label: CityDes
                    name: cityDes
                    widget: object
                    fields: 
                      - label: Toronto
                        name : toronto
                        widget: object
                        fields: 
                          - {name: title, label: cityTile, widget: string}
                          - {name: img, label: Img, widget: image}
                          - {name: des, label: Des, widget: text}

                      
                      - label: Chicago
                        name : chicago
                        widget: object
                        fields: 
                          - {name: title, label: cityTile, widget: string}
                          - {name: img, label: Img, widget: image}
                          - {name: des, label: Des, widget: text}

                      - label: Shanghai
                        name : shanghai
                        widget: object
                        fields: 
                          - {name: title, label: cityTile, widget: string}
                          - {name: img, label: Img, widget: image}
                          - {name: des, label: Des, widget: text}

                      - label: xian
                        name : xian
                        widget: object
                        fields: 
                          - {name: title, label: cityTile, widget: string}
                          - {name: img, label: Img, widget: image}
                          - {name: des, label: Des, widget: text}

                      



      





