backend:
  name: git-gateway
  branch: master



media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: src/markdownPage
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: pagesContent
    label: PagesContent
    files:
      - file: src/pageContent/index.md
        name: home
        label: HomePage
        fields: 
          - { name: aboutTitle, label: AboutTitle, widget: string }
          - { name: aboutMe, label: AboutMe, widget: text }




